version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Scanning CloudFormation template..."
      - python scan_template.py  # This script calls Conformity API
artifacts:
  files:
    - results.json
